---
# tasks file for roles/memcached
- name: 'install memcached'
  yum:
    update_cache: yes
    name:
      - memcached
    state: present

- name: 'restart memcached'
  systemd:
    state: started
    enabled: yes
    name: memcached
