---

- name: 'Install_requiered_packages'
  apt:
    name:
      - wget
      - software-properties-common
      - lsb-release
      - ca-certificates
      - apt-transport-https
    state: present

- name: 'install'
  command: add-apt-repository ppa:ondrej/php -y

- name: 'Install php-fpm71'
  apt:
   name: php7.1-fpm
