---
# tasks file for roles_rpm_packages/perconadb
- name: 'Install percona'
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm

- name: 'systemd started-enabled'
  systemd:
    name: mysqld
    enabled: yes
    state: started
