---
# tasks file for roles_rpm_packages/redis
- name: 'install required packages'
  yum:
    name:
      - epel-release
- name: 'install redis'
  yum:
    name:
      - redis
    state: present

- name: 'systemd enable start'
  systemd:
    name: redis
    enabled: yes
    state: started
