---

- name: 'Install_requiered_packages'
  apt:
    name:
      - wget
      - software-properties-common
      - lsb-release
      - ca-certificates
      - apt-transport-https
    state: present

- name: 'install'
  command: add-apt-repository ppa:ondrej/php

# - name: 'Install php-fpm71'
#  apt:
#    name: php-fpm7.1
